/*
================================================================================
TRABALHO 2 - IMPLEMENTAÇÃO DE BANCO DE DADOS PARA UMA CLÍNICA
SGBD: PostgreSQL

Conteúdo do script:
1. Criação do schema
2. DDL com restrições de integridade: NOT NULL, UNIQUE, CHECK e FOREIGN KEY
3. Carga de dados fictícios
4. Views para relatórios
5. Triggers e Stored Procedures
6. Consultas SQL complexas com JOIN, GROUP BY, HAVING e subconsultas
7. Teste de transação demonstrando propriedades ACID
8. Roles e permissões de segurança
================================================================================
*/

-- ============================================================================
-- 1. PREPARAÇÃO DO AMBIENTE
-- ============================================================================

DROP SCHEMA IF EXISTS clinica CASCADE;
CREATE SCHEMA clinica;
SET search_path TO clinica;

-- ============================================================================
-- 2. DDL - CRIAÇÃO DAS TABELAS
-- ============================================================================

CREATE TABLE status (
    id_status INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(30) NOT NULL UNIQUE,
    CONSTRAINT chk_status_descricao CHECK (descricao IN ('Agendado', 'Realizado', 'Cancelado', 'Pendente'))
);

CREATE TABLE paciente (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_paciente VARCHAR(120) NOT NULL,
    data_nascimento DATE NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(120) UNIQUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_paciente_cpf CHECK (cpf ~ '^[0-9]{3}\.[0-9]{3}\.[0-9]{3}-[0-9]{2}$'),
    CONSTRAINT chk_paciente_nascimento CHECK (data_nascimento <= CURRENT_DATE),
    CONSTRAINT chk_paciente_email CHECK (email IS NULL OR email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

CREATE TABLE endereco (
    id_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    logradouro VARCHAR(150) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    bairro VARCHAR(80) NOT NULL,
    cidade VARCHAR(80) NOT NULL,
    uf CHAR(2) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    tipo_endereco VARCHAR(30) NOT NULL DEFAULT 'Residencial',
    CONSTRAINT fk_endereco_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT chk_endereco_uf CHECK (uf ~ '^[A-Z]{2}$'),
    CONSTRAINT chk_endereco_cep CHECK (cep ~ '^[0-9]{5}-[0-9]{3}$'),
    CONSTRAINT chk_endereco_tipo CHECK (tipo_endereco IN ('Residencial', 'Comercial', 'Outro')),
    CONSTRAINT uq_endereco_paciente_tipo UNIQUE (id_paciente, tipo_endereco, cep, numero)
);

CREATE TABLE funcionario (
    id_funcionario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_funcionario VARCHAR(120) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    ctps VARCHAR(20) NOT NULL UNIQUE,
    cargo VARCHAR(40) NOT NULL,
    especialidade VARCHAR(80),
    crm VARCHAR(20) UNIQUE,
    salario NUMERIC(10,2) NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_funcionario_cpf CHECK (cpf ~ '^[0-9]{3}\.[0-9]{3}\.[0-9]{3}-[0-9]{2}$'),
    CONSTRAINT chk_funcionario_cargo CHECK (cargo IN ('Médico', 'Recepcionista', 'Técnico', 'Enfermeiro', 'Administrador')),
    CONSTRAINT chk_funcionario_salario CHECK (salario >= 0),
    CONSTRAINT chk_funcionario_medico_crm CHECK (
        (cargo = 'Médico' AND crm IS NOT NULL)
        OR
        (cargo <> 'Médico')
    )
);

CREATE TABLE telefone (
    id_telefone INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER,
    id_funcionario INTEGER,
    numero VARCHAR(16) NOT NULL UNIQUE,
    tipo_telefone VARCHAR(20) NOT NULL,
    CONSTRAINT fk_telefone_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_telefone_funcionario FOREIGN KEY (id_funcionario)
        REFERENCES funcionario (id_funcionario)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT chk_telefone_tipo CHECK (tipo_telefone IN ('Celular', 'Residencial', 'Comercial', 'Emergência')),
    CONSTRAINT chk_telefone_numero CHECK (numero ~ '^\([0-9]{2}\) [0-9]{4,5}-[0-9]{4}$'),
    CONSTRAINT chk_telefone_dono CHECK (
        (id_paciente IS NOT NULL AND id_funcionario IS NULL)
        OR
        (id_paciente IS NULL AND id_funcionario IS NOT NULL)
    )
);

CREATE TABLE agendamento (
    id_agendamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_funcionario INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    data_agendamento DATE NOT NULL,
    hora_agendamento TIME NOT NULL,
    observacao TEXT,
    valor_consulta NUMERIC(10,2) NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agendamento_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_agendamento_funcionario FOREIGN KEY (id_funcionario)
        REFERENCES funcionario (id_funcionario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_agendamento_status FOREIGN KEY (id_status)
        REFERENCES status (id_status)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_agendamento_horario CHECK (hora_agendamento BETWEEN TIME '07:00' AND TIME '20:00'),
    CONSTRAINT chk_agendamento_valor CHECK (valor_consulta >= 0)
);

CREATE TABLE exame (
    id_exame INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_agendamento INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    tipo_exame VARCHAR(80) NOT NULL,
    descricao TEXT,
    resultado TEXT,
    data_exame DATE NOT NULL,
    hora_exame TIME NOT NULL,
    valor_exame NUMERIC(10,2) NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exame_agendamento FOREIGN KEY (id_agendamento)
        REFERENCES agendamento (id_agendamento)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_exame_status FOREIGN KEY (id_status)
        REFERENCES status (id_status)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_exame_horario CHECK (hora_exame BETWEEN TIME '07:00' AND TIME '20:00'),
    CONSTRAINT chk_exame_valor CHECK (valor_exame >= 0)
);

CREATE TABLE exame_funcionario (
    id_funcionario INTEGER NOT NULL,
    id_exame INTEGER NOT NULL,
    papel VARCHAR(40) NOT NULL DEFAULT 'Responsável',
    PRIMARY KEY (id_funcionario, id_exame),
    CONSTRAINT fk_exame_funcionario_funcionario FOREIGN KEY (id_funcionario)
        REFERENCES funcionario (id_funcionario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_exame_funcionario_exame FOREIGN KEY (id_exame)
        REFERENCES exame (id_exame)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT chk_exame_funcionario_papel CHECK (papel IN ('Responsável', 'Auxiliar', 'Solicitante'))
);

-- Tabela auxiliar criada apenas para o teste de transação ACID solicitado na proposta.
CREATE TABLE conta_financeira (
    id_conta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_conta VARCHAR(80) NOT NULL UNIQUE,
    saldo NUMERIC(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT chk_conta_saldo CHECK (saldo >= 0)
);

CREATE TABLE log_auditoria (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_afetada VARCHAR(80) NOT NULL,
    operacao VARCHAR(20) NOT NULL,
    descricao TEXT NOT NULL,
    data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 3. FUNÇÕES, TRIGGERS E STORED PROCEDURES
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_atualizar_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_paciente_timestamp
BEFORE UPDATE ON paciente
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_timestamp();

CREATE TRIGGER trg_funcionario_timestamp
BEFORE UPDATE ON funcionario
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_timestamp();

CREATE TRIGGER trg_agendamento_timestamp
BEFORE UPDATE ON agendamento
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_timestamp();

CREATE TRIGGER trg_exame_timestamp
BEFORE UPDATE ON exame
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_timestamp();

CREATE OR REPLACE FUNCTION fn_validar_agendamento()
RETURNS TRIGGER AS $$
DECLARE
    v_status_descricao VARCHAR(30);
    v_funcionario_ativo BOOLEAN;
    v_cargo VARCHAR(40);
BEGIN
    SELECT descricao
      INTO v_status_descricao
      FROM status
     WHERE id_status = NEW.id_status;

    SELECT ativo, cargo
      INTO v_funcionario_ativo, v_cargo
      FROM funcionario
     WHERE id_funcionario = NEW.id_funcionario;

    IF v_funcionario_ativo IS DISTINCT FROM TRUE THEN
        RAISE EXCEPTION 'Não é permitido agendar consulta para funcionário inativo.';
    END IF;

    IF v_cargo NOT IN ('Médico', 'Enfermeiro') THEN
        RAISE EXCEPTION 'Somente médico ou enfermeiro pode ser responsável por agendamento clínico.';
    END IF;

    IF v_status_descricao = 'Cancelado' AND COALESCE(TRIM(NEW.observacao), '') = '' THEN
        RAISE EXCEPTION 'Agendamento cancelado precisa possuir observação com motivo.';
    END IF;

    IF v_status_descricao <> 'Cancelado' THEN
        IF EXISTS (
            SELECT 1
              FROM agendamento a
              JOIN status s ON s.id_status = a.id_status
             WHERE a.id_funcionario = NEW.id_funcionario
               AND a.data_agendamento = NEW.data_agendamento
               AND a.hora_agendamento = NEW.hora_agendamento
               AND s.descricao <> 'Cancelado'
               AND a.id_agendamento <> COALESCE(NEW.id_agendamento, -1)
        ) THEN
            RAISE EXCEPTION 'Funcionário já possui agendamento neste dia e horário.';
        END IF;

        IF EXISTS (
            SELECT 1
              FROM agendamento a
              JOIN status s ON s.id_status = a.id_status
             WHERE a.id_paciente = NEW.id_paciente
               AND a.data_agendamento = NEW.data_agendamento
               AND a.hora_agendamento = NEW.hora_agendamento
               AND s.descricao <> 'Cancelado'
               AND a.id_agendamento <> COALESCE(NEW.id_agendamento, -1)
        ) THEN
            RAISE EXCEPTION 'Paciente já possui agendamento neste dia e horário.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_agendamento
BEFORE INSERT OR UPDATE ON agendamento
FOR EACH ROW
EXECUTE FUNCTION fn_validar_agendamento();

CREATE OR REPLACE FUNCTION fn_validar_exame()
RETURNS TRIGGER AS $$
DECLARE
    v_status_agendamento VARCHAR(30);
    v_data_agendamento DATE;
BEGIN
    SELECT s.descricao, a.data_agendamento
      INTO v_status_agendamento, v_data_agendamento
      FROM agendamento a
      JOIN status s ON s.id_status = a.id_status
     WHERE a.id_agendamento = NEW.id_agendamento;

    IF v_status_agendamento = 'Cancelado' THEN
        RAISE EXCEPTION 'Não é permitido cadastrar exame para agendamento cancelado.';
    END IF;

    IF NEW.data_exame < v_data_agendamento THEN
        RAISE EXCEPTION 'Data do exame não pode ser anterior à data do agendamento.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_exame
BEFORE INSERT OR UPDATE ON exame
FOR EACH ROW
EXECUTE FUNCTION fn_validar_exame();

CREATE OR REPLACE FUNCTION fn_log_agendamento()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO log_auditoria (tabela_afetada, operacao, descricao)
    VALUES (
        'agendamento',
        TG_OP,
        'Agendamento ID ' || COALESCE(NEW.id_agendamento, OLD.id_agendamento) || ' sofreu operação ' || TG_OP
    );

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_log_agendamento
AFTER INSERT OR UPDATE OR DELETE ON agendamento
FOR EACH ROW
EXECUTE FUNCTION fn_log_agendamento();

CREATE OR REPLACE PROCEDURE sp_criar_agendamento(
    p_id_paciente INTEGER,
    p_id_funcionario INTEGER,
    p_data_agendamento DATE,
    p_hora_agendamento TIME,
    p_observacao TEXT DEFAULT NULL,
    p_valor_consulta NUMERIC DEFAULT 0
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_status_agendado INTEGER;
BEGIN
    SELECT id_status
      INTO v_status_agendado
      FROM status
     WHERE descricao = 'Agendado';

    IF v_status_agendado IS NULL THEN
        RAISE EXCEPTION 'Status Agendado não cadastrado.';
    END IF;

    INSERT INTO agendamento (
        id_paciente,
        id_funcionario,
        id_status,
        data_agendamento,
        hora_agendamento,
        observacao,
        valor_consulta
    ) VALUES (
        p_id_paciente,
        p_id_funcionario,
        v_status_agendado,
        p_data_agendamento,
        p_hora_agendamento,
        p_observacao,
        p_valor_consulta
    );
END;
$$;

CREATE OR REPLACE PROCEDURE sp_cancelar_agendamento(
    p_id_agendamento INTEGER,
    p_motivo TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_status_cancelado INTEGER;
BEGIN
    IF COALESCE(TRIM(p_motivo), '') = '' THEN
        RAISE EXCEPTION 'É obrigatório informar o motivo do cancelamento.';
    END IF;

    SELECT id_status
      INTO v_status_cancelado
      FROM status
     WHERE descricao = 'Cancelado';

    IF v_status_cancelado IS NULL THEN
        RAISE EXCEPTION 'Status Cancelado não cadastrado.';
    END IF;

    UPDATE agendamento
       SET id_status = v_status_cancelado,
           observacao = COALESCE(observacao || ' | ', '') || 'Cancelado: ' || p_motivo
     WHERE id_agendamento = p_id_agendamento;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Agendamento % não encontrado.', p_id_agendamento;
    END IF;

    UPDATE exame
       SET id_status = v_status_cancelado
     WHERE id_agendamento = p_id_agendamento;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_transferir_valor(
    p_id_conta_origem INTEGER,
    p_id_conta_destino INTEGER,
    p_valor NUMERIC
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_saldo_origem NUMERIC(12,2);
BEGIN
    IF p_valor <= 0 THEN
        RAISE EXCEPTION 'Valor de transferência deve ser maior que zero.';
    END IF;

    IF p_id_conta_origem = p_id_conta_destino THEN
        RAISE EXCEPTION 'Conta de origem e destino não podem ser iguais.';
    END IF;

    SELECT saldo
      INTO v_saldo_origem
      FROM conta_financeira
     WHERE id_conta = p_id_conta_origem
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Conta de origem não encontrada.';
    END IF;

    PERFORM 1
      FROM conta_financeira
     WHERE id_conta = p_id_conta_destino
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Conta de destino não encontrada.';
    END IF;

    IF v_saldo_origem < p_valor THEN
        RAISE EXCEPTION 'Saldo insuficiente para transferência. Saldo atual: %', v_saldo_origem;
    END IF;

    UPDATE conta_financeira
       SET saldo = saldo - p_valor
     WHERE id_conta = p_id_conta_origem;

    UPDATE conta_financeira
       SET saldo = saldo + p_valor
     WHERE id_conta = p_id_conta_destino;
END;
$$;

-- ============================================================================
-- 4. CARGA DE DADOS FICTÍCIOS
-- ============================================================================

INSERT INTO status (id_status, descricao) VALUES
(1, 'Agendado'),
(2, 'Realizado'),
(3, 'Cancelado'),
(4, 'Pendente');

INSERT INTO paciente (id_paciente, nome_paciente, data_nascimento, cpf, email) VALUES
(1, 'Ana Paula Ribeiro', '1990-03-12', '123.456.789-01', 'ana.ribeiro@email.com'),
(2, 'Carlos Eduardo Lima', '1985-07-22', '987.654.321-00', 'carlos.lima@email.com'),
(3, 'Mariana Costa', '2001-11-05', '456.789.123-45', 'mariana.costa@email.com'),
(4, 'Roberto Martins', '1978-01-30', '321.654.987-10', 'roberto.martins@email.com'),
(5, 'Juliana Almeida', '1995-09-18', '741.852.963-12', 'juliana.almeida@email.com'),
(6, 'Pedro Henrique Souza', '1969-06-10', '852.963.741-13', 'pedro.souza@email.com');

INSERT INTO endereco (id_endereco, id_paciente, logradouro, numero, bairro, cidade, uf, cep, tipo_endereco) VALUES
(1, 1, 'Rua das Flores', '123', 'Centro', 'Porto Alegre', 'RS', '90010-000', 'Residencial'),
(2, 1, 'Avenida Borges', '500', 'Praia de Belas', 'Porto Alegre', 'RS', '90110-150', 'Comercial'),
(3, 2, 'Rua Anita Garibaldi', '45', 'Boa Vista', 'Porto Alegre', 'RS', '90480-200', 'Residencial'),
(4, 3, 'Rua São João', '88', 'Centro', 'Canoas', 'RS', '92010-330', 'Residencial'),
(5, 4, 'Avenida Ipiranga', '1200', 'Partenon', 'Porto Alegre', 'RS', '90610-000', 'Residencial'),
(6, 5, 'Rua Bento Gonçalves', '321', 'Centro', 'Guaíba', 'RS', '92500-000', 'Residencial'),
(7, 6, 'Rua Padre Cacique', '777', 'Menino Deus', 'Porto Alegre', 'RS', '90810-240', 'Residencial');

INSERT INTO funcionario (id_funcionario, nome_funcionario, cpf, ctps, cargo, especialidade, crm, salario, ativo) VALUES
(1, 'Dr. Ricardo Nunes', '111.222.333-44', 'CTPS001', 'Médico', 'Clínico Geral', 'CRM-RS-1001', 12500.00, TRUE),
(2, 'Dra. Fernanda Torres', '222.333.444-55', 'CTPS002', 'Médico', 'Cardiologia', 'CRM-RS-1002', 15400.00, TRUE),
(3, 'Paula Machado', '333.444.555-66', 'CTPS003', 'Recepcionista', NULL, NULL, 2800.00, TRUE),
(4, 'Bruno Silveira', '444.555.666-77', 'CTPS004', 'Técnico', 'Radiologia', NULL, 4200.00, TRUE),
(5, 'Enf. Larissa Oliveira', '555.666.777-88', 'CTPS005', 'Enfermeiro', 'Triagem', NULL, 5200.00, TRUE),
(6, 'Marcos Pereira', '666.777.888-99', 'CTPS006', 'Administrador', NULL, NULL, 6500.00, TRUE);

INSERT INTO telefone (id_telefone, id_paciente, id_funcionario, numero, tipo_telefone) VALUES
(1, 1, NULL, '(51) 99999-1001', 'Celular'),
(2, 2, NULL, '(51) 99999-1002', 'Celular'),
(3, 3, NULL, '(51) 99999-1003', 'Celular'),
(4, 4, NULL, '(51) 99999-1004', 'Celular'),
(5, 5, NULL, '(51) 99999-1005', 'Celular'),
(6, 6, NULL, '(51) 99999-1006', 'Celular'),
(7, NULL, 1, '(51) 3333-1001', 'Comercial'),
(8, NULL, 2, '(51) 3333-1002', 'Comercial'),
(9, NULL, 3, '(51) 3333-1003', 'Comercial'),
(10, NULL, 4, '(51) 3333-1004', 'Comercial');

INSERT INTO agendamento (id_agendamento, id_paciente, id_funcionario, id_status, data_agendamento, hora_agendamento, observacao, valor_consulta) VALUES
(1, 1, 1, 2, '2026-07-01', '08:30', 'Consulta de rotina realizada.', 180.00),
(2, 2, 2, 1, '2026-07-01', '10:00', 'Primeira consulta cardiológica.', 250.00),
(3, 3, 1, 4, '2026-07-02', '09:30', 'Aguardando confirmação do paciente.', 180.00),
(4, 4, 5, 1, '2026-07-02', '11:00', 'Triagem inicial.', 120.00),
(5, 5, 2, 2, '2026-07-03', '14:00', 'Consulta realizada com solicitação de exame.', 250.00),
(6, 1, 2, 3, '2026-07-04', '15:00', 'Cancelado: paciente solicitou remarcação.', 250.00),
(7, 6, 1, 1, '2026-07-05', '16:00', 'Consulta clínica geral.', 180.00),
(8, 2, 1, 2, '2026-07-06', '08:00', 'Retorno realizado.', 150.00),
(9, 3, 2, 1, '2026-07-06', '09:00', 'Avaliação cardiológica.', 250.00),
(10, 4, 1, 1, '2026-07-07', '13:30', 'Consulta clínica geral.', 180.00);

INSERT INTO exame (id_exame, id_agendamento, id_status, tipo_exame, descricao, resultado, data_exame, hora_exame, valor_exame) VALUES
(1, 1, 2, 'Hemograma', 'Exame de sangue completo.', 'Resultados dentro da normalidade.', '2026-07-01', '09:30', 65.00),
(2, 2, 4, 'Eletrocardiograma', 'Avaliação da atividade elétrica do coração.', NULL, '2026-07-01', '11:00', 120.00),
(3, 5, 2, 'Raio-X', 'Exame de imagem solicitado em consulta.', 'Sem alterações relevantes.', '2026-07-03', '15:00', 180.00),
(4, 5, 1, 'Ultrassom', 'Ultrassonografia abdominal.', NULL, '2026-07-04', '10:30', 220.00),
(5, 8, 2, 'Glicemia', 'Avaliação de glicose em jejum.', 'Glicose dentro do intervalo de referência.', '2026-07-06', '09:00', 45.00),
(6, 9, 4, 'Ecocardiograma', 'Exame complementar cardiológico.', NULL, '2026-07-06', '10:30', 320.00),
(7, 10, 1, 'Hemograma', 'Solicitado para avaliação geral.', NULL, '2026-07-07', '14:30', 65.00);

INSERT INTO exame_funcionario (id_funcionario, id_exame, papel) VALUES
(1, 1, 'Solicitante'),
(2, 2, 'Solicitante'),
(4, 3, 'Responsável'),
(2, 4, 'Solicitante'),
(1, 5, 'Solicitante'),
(2, 6, 'Solicitante'),
(1, 7, 'Solicitante');

INSERT INTO conta_financeira (id_conta, nome_conta, saldo) VALUES
(1, 'Conta Caixa Clínica', 5000.00),
(2, 'Conta Banco Clínica', 1500.00);

-- Ajuste das sequences após inserir IDs manualmente.
SELECT setval(pg_get_serial_sequence('status', 'id_status'), (SELECT MAX(id_status) FROM status));
SELECT setval(pg_get_serial_sequence('paciente', 'id_paciente'), (SELECT MAX(id_paciente) FROM paciente));
SELECT setval(pg_get_serial_sequence('endereco', 'id_endereco'), (SELECT MAX(id_endereco) FROM endereco));
SELECT setval(pg_get_serial_sequence('funcionario', 'id_funcionario'), (SELECT MAX(id_funcionario) FROM funcionario));
SELECT setval(pg_get_serial_sequence('telefone', 'id_telefone'), (SELECT MAX(id_telefone) FROM telefone));
SELECT setval(pg_get_serial_sequence('agendamento', 'id_agendamento'), (SELECT MAX(id_agendamento) FROM agendamento));
SELECT setval(pg_get_serial_sequence('exame', 'id_exame'), (SELECT MAX(id_exame) FROM exame));
SELECT setval(pg_get_serial_sequence('conta_financeira', 'id_conta'), (SELECT MAX(id_conta) FROM conta_financeira));

-- ============================================================================
-- 5. VIEWS PARA RELATÓRIOS E SEGURANÇA
-- ============================================================================

CREATE OR REPLACE VIEW vw_agendamentos_detalhados AS
SELECT
    a.id_agendamento,
    p.nome_paciente,
    p.cpf AS cpf_paciente,
    f.nome_funcionario,
    f.cargo,
    f.especialidade,
    s.descricao AS status_agendamento,
    a.data_agendamento,
    a.hora_agendamento,
    a.valor_consulta,
    a.observacao
FROM agendamento a
JOIN paciente p ON p.id_paciente = a.id_paciente
JOIN funcionario f ON f.id_funcionario = a.id_funcionario
JOIN status s ON s.id_status = a.id_status;

CREATE OR REPLACE VIEW vw_exames_detalhados AS
SELECT
    e.id_exame,
    e.tipo_exame,
    e.data_exame,
    e.hora_exame,
    e.valor_exame,
    se.descricao AS status_exame,
    p.nome_paciente,
    f.nome_funcionario AS profissional_agendamento,
    sa.descricao AS status_agendamento
FROM exame e
JOIN agendamento a ON a.id_agendamento = e.id_agendamento
JOIN paciente p ON p.id_paciente = a.id_paciente
JOIN funcionario f ON f.id_funcionario = a.id_funcionario
JOIN status se ON se.id_status = e.id_status
JOIN status sa ON sa.id_status = a.id_status;

CREATE OR REPLACE VIEW vw_relatorio_financeiro_agendamentos AS
SELECT
    p.nome_paciente,
    COUNT(a.id_agendamento) AS total_agendamentos,
    COALESCE(SUM(a.valor_consulta), 0) AS total_consultas,
    COALESCE(SUM(e.valor_exame), 0) AS total_exames,
    COALESCE(SUM(a.valor_consulta), 0) + COALESCE(SUM(e.valor_exame), 0) AS total_geral
FROM paciente p
LEFT JOIN agendamento a ON a.id_paciente = p.id_paciente
LEFT JOIN exame e ON e.id_agendamento = a.id_agendamento
GROUP BY p.id_paciente, p.nome_paciente;

CREATE OR REPLACE VIEW vw_exames_pendentes AS
SELECT
    e.id_exame,
    e.tipo_exame,
    p.nome_paciente,
    e.data_exame,
    e.hora_exame,
    s.descricao AS status_exame
FROM exame e
JOIN status s ON s.id_status = e.id_status
JOIN agendamento a ON a.id_agendamento = e.id_agendamento
JOIN paciente p ON p.id_paciente = a.id_paciente
WHERE s.descricao IN ('Agendado', 'Pendente');

-- ============================================================================
-- 6. CONSULTAS SQL COMPLEXAS
-- ============================================================================

-- Consulta 1: Agendamentos detalhados com múltiplos JOINs.
SELECT
    a.id_agendamento,
    p.nome_paciente,
    f.nome_funcionario,
    f.especialidade,
    s.descricao AS status,
    a.data_agendamento,
    a.hora_agendamento
FROM agendamento a
JOIN paciente p ON p.id_paciente = a.id_paciente
JOIN funcionario f ON f.id_funcionario = a.id_funcionario
JOIN status s ON s.id_status = a.id_status
ORDER BY a.data_agendamento, a.hora_agendamento;

-- Consulta 2: Quantidade de agendamentos por funcionário.
SELECT
    f.nome_funcionario,
    f.cargo,
    COUNT(a.id_agendamento) AS total_agendamentos
FROM funcionario f
LEFT JOIN agendamento a ON a.id_funcionario = f.id_funcionario
GROUP BY f.id_funcionario, f.nome_funcionario, f.cargo
ORDER BY total_agendamentos DESC;

-- Consulta 3: Pacientes com mais de um agendamento, usando GROUP BY e HAVING.
SELECT
    p.nome_paciente,
    COUNT(a.id_agendamento) AS total_agendamentos
FROM paciente p
JOIN agendamento a ON a.id_paciente = p.id_paciente
GROUP BY p.id_paciente, p.nome_paciente
HAVING COUNT(a.id_agendamento) > 1
ORDER BY total_agendamentos DESC;

-- Consulta 4: Total arrecadado por status de agendamento.
SELECT
    s.descricao AS status_agendamento,
    COUNT(a.id_agendamento) AS quantidade,
    SUM(a.valor_consulta) AS total_consultas
FROM status s
JOIN agendamento a ON a.id_status = s.id_status
GROUP BY s.descricao
ORDER BY total_consultas DESC;

-- Consulta 5: Exames por paciente com valor total, incluindo JOINs múltiplos.
SELECT
    p.nome_paciente,
    COUNT(e.id_exame) AS quantidade_exames,
    SUM(e.valor_exame) AS valor_total_exames
FROM paciente p
JOIN agendamento a ON a.id_paciente = p.id_paciente
JOIN exame e ON e.id_agendamento = a.id_agendamento
GROUP BY p.id_paciente, p.nome_paciente
ORDER BY valor_total_exames DESC;

-- Consulta 6: Pacientes que possuem exames pendentes usando subconsulta.
SELECT
    p.nome_paciente,
    p.cpf
FROM paciente p
WHERE p.id_paciente IN (
    SELECT a.id_paciente
    FROM agendamento a
    JOIN exame e ON e.id_agendamento = a.id_agendamento
    JOIN status s ON s.id_status = e.id_status
    WHERE s.descricao = 'Pendente'
)
ORDER BY p.nome_paciente;

-- Consulta 7: Funcionários que solicitaram ou realizaram mais de um exame.
SELECT
    f.nome_funcionario,
    f.cargo,
    COUNT(ef.id_exame) AS total_exames_relacionados
FROM funcionario f
JOIN exame_funcionario ef ON ef.id_funcionario = f.id_funcionario
GROUP BY f.id_funcionario, f.nome_funcionario, f.cargo
HAVING COUNT(ef.id_exame) > 1
ORDER BY total_exames_relacionados DESC;

-- Consulta 8: Próximo agendamento de cada paciente com subconsulta correlacionada.
SELECT
    p.nome_paciente,
    (
        SELECT MIN(a2.data_agendamento)
        FROM agendamento a2
        JOIN status s2 ON s2.id_status = a2.id_status
        WHERE a2.id_paciente = p.id_paciente
          AND s2.descricao <> 'Cancelado'
    ) AS proxima_data_agendamento
FROM paciente p
ORDER BY p.nome_paciente;

-- Consulta 9: Telefones e endereços agrupados por paciente.
SELECT
    p.nome_paciente,
    STRING_AGG(DISTINCT t.numero, ', ') AS telefones,
    STRING_AGG(DISTINCT e.logradouro || ', ' || e.numero || ' - ' || e.cidade || '/' || e.uf, ' | ') AS enderecos
FROM paciente p
LEFT JOIN telefone t ON t.id_paciente = p.id_paciente
LEFT JOIN endereco e ON e.id_paciente = p.id_paciente
GROUP BY p.id_paciente, p.nome_paciente
ORDER BY p.nome_paciente;

-- Consulta 10: Média de valor de consultas por especialidade, filtrando especialidades com média acima de 180.
SELECT
    f.especialidade,
    COUNT(a.id_agendamento) AS total_consultas,
    ROUND(AVG(a.valor_consulta), 2) AS media_valor_consulta
FROM funcionario f
JOIN agendamento a ON a.id_funcionario = f.id_funcionario
WHERE f.especialidade IS NOT NULL
GROUP BY f.especialidade
HAVING AVG(a.valor_consulta) > 180
ORDER BY media_valor_consulta DESC;

-- ============================================================================
-- 7. TESTE DE LÓGICA / PROCEDURES
-- ============================================================================

-- Criação de um agendamento via Stored Procedure.
CALL sp_criar_agendamento(5, 1, '2026-07-08', '10:00', 'Consulta criada pela procedure.', 180.00);

-- Cancelamento de agendamento via Stored Procedure.
CALL sp_cancelar_agendamento(3, 'Paciente não confirmou presença.');

-- Exemplo de teste da Trigger de conflito de horário.
-- Deve gerar erro, pois o funcionário 1 já possui agendamento em 2026-07-01 às 08:30.
-- Descomente para testar:
-- CALL sp_criar_agendamento(2, 1, '2026-07-01', '08:30', 'Teste de conflito.', 180.00);

-- ============================================================================
-- 8. TESTE ACID COM TRANSAÇÃO
-- ============================================================================

-- Situação inicial das contas.
SELECT * FROM conta_financeira ORDER BY id_conta;

-- Atomicidade, Consistência, Isolamento e Durabilidade:
-- A transferência só será confirmada se débito e crédito ocorrerem com sucesso.
BEGIN;
    CALL sp_transferir_valor(1, 2, 200.00);
COMMIT;

SELECT * FROM conta_financeira ORDER BY id_conta;

-- Demonstração de ROLLBACK manual.
-- O saldo será alterado dentro da transação, mas voltará ao valor anterior após o ROLLBACK.
BEGIN;
    UPDATE conta_financeira
       SET saldo = saldo - 300.00
     WHERE id_conta = 1;

    UPDATE conta_financeira
       SET saldo = saldo + 300.00
     WHERE id_conta = 2;

    SELECT * FROM conta_financeira ORDER BY id_conta;
ROLLBACK;

SELECT * FROM conta_financeira ORDER BY id_conta;

-- Demonstração de erro tratado: tentativa de transferir valor maior que o saldo.
DO $$
BEGIN
    BEGIN
        CALL sp_transferir_valor(1, 2, 999999.00);
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Erro esperado capturado. A transferência foi desfeita: %', SQLERRM;
    END;
END;
$$;

SELECT * FROM conta_financeira ORDER BY id_conta;

-- ============================================================================
-- 9. SEGURANÇA - ROLES E PERMISSÕES
-- ============================================================================

-- Observação: para executar CREATE ROLE, o usuário do PostgreSQL precisa ter permissão administrativa.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'clinica_admin') THEN
        CREATE ROLE clinica_admin NOLOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'clinica_atendimento') THEN
        CREATE ROLE clinica_atendimento NOLOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'clinica_relatorio') THEN
        CREATE ROLE clinica_relatorio NOLOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'usuario_admin_clinica') THEN
        CREATE ROLE usuario_admin_clinica LOGIN PASSWORD 'Admin@123';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'usuario_atendimento_clinica') THEN
        CREATE ROLE usuario_atendimento_clinica LOGIN PASSWORD 'Atendimento@123';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'usuario_relatorio_clinica') THEN
        CREATE ROLE usuario_relatorio_clinica LOGIN PASSWORD 'Relatorio@123';
    END IF;
END;
$$;

GRANT clinica_admin TO usuario_admin_clinica;
GRANT clinica_atendimento TO usuario_atendimento_clinica;
GRANT clinica_relatorio TO usuario_relatorio_clinica;

REVOKE ALL ON SCHEMA clinica FROM PUBLIC;
GRANT USAGE ON SCHEMA clinica TO clinica_admin, clinica_atendimento, clinica_relatorio;

-- Administrador: acesso total ao schema.
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA clinica TO clinica_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA clinica TO clinica_admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA clinica TO clinica_admin;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA clinica TO clinica_admin;

-- Atendimento: pode consultar e manipular dados operacionais, mas não acessa tabela financeira.
GRANT SELECT, INSERT, UPDATE ON paciente, endereco, telefone, agendamento, exame TO clinica_atendimento;
GRANT SELECT ON status, funcionario TO clinica_atendimento;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA clinica TO clinica_atendimento;
GRANT EXECUTE ON PROCEDURE sp_criar_agendamento(INTEGER, INTEGER, DATE, TIME, TEXT, NUMERIC) TO clinica_atendimento;
GRANT EXECUTE ON PROCEDURE sp_cancelar_agendamento(INTEGER, TEXT) TO clinica_atendimento;

-- Relatório: acesso apenas às views de consulta.
GRANT SELECT ON vw_agendamentos_detalhados TO clinica_relatorio;
GRANT SELECT ON vw_exames_detalhados TO clinica_relatorio;
GRANT SELECT ON vw_relatorio_financeiro_agendamentos TO clinica_relatorio;
GRANT SELECT ON vw_exames_pendentes TO clinica_relatorio;

-- Garantia de que o usuário de relatório não acessa tabelas diretamente.
REVOKE ALL ON paciente, endereco, telefone, funcionario, agendamento, exame, exame_funcionario, conta_financeira, log_auditoria FROM clinica_relatorio;

-- ============================================================================
-- FIM DO SCRIPT
-- ============================================================================
